version: '3.8'

services:
  db-test:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306" 
    volumes:
      - db-test-data:/var/lib/mysql

volumes:
  db-test-data:
